/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.selenium.quick.start.java;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
